name: {{ project.libname }}
version: 0.0.1
description:
  {{ project.description }}
author: {{ project.author }}
homepage: {{ project.homepage}}
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  yaml: ">=2.0.1+1 <3.0.0"
  play_phaser: ">=0.10.3+1 <0.11.0"
  play_pixi: ">=0.10.3 <0.11.0"
  dilithium: ">=0.1.0 <0.2.0"

transformers:
- $dart2js:
    checked: false
    minify: true
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true
    csp: true
