// Generated by CoffeeScript 1.8.0
var lib,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

lib = require('../../lib');

lib.Li2State = (function(_super) {
  __extends(Li2State, _super);

  function Li2State() {
    return Li2State.__super__.constructor.apply(this, arguments);
  }

  Li2State.prototype.addButton = function(x, y, key, style, text, callback) {
    var button;
    button = new lib.Li2Button(this.game, x, y, key, style, text, callback);
    this.add.group().add(button);
    return button;
  };

  return Li2State;

})(Phaser.State);

//# sourceMappingURL=li2_state.js.map
