// Generated by CoffeeScript 1.8.0
var lib,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

lib = require('../../lib');

lib.Li2Button = (function(_super) {
  __extends(Li2Button, _super);

  Li2Button.prototype.label = null;

  function Li2Button(game, x, y, key, style, text, callback) {
    Li2Button.__super__.constructor.call(this, game, x, y, key, callback);
    this.label = new Phaser.Text(game, 0, 0, text, style);
    addChild(this.label);
    setLabel(text);
  }

  Li2Button.prototype.setLabel = function(text) {
    this.label.setText(text);
    this.label.x = Math.floor((this.width - this.label.width) / 2);
    return this.label.y = Math.floor((this.height - this.label.height) / 2);
  };

  return Li2Button;

})(Phaser.Button);

//# sourceMappingURL=li2_button.js.map
