// Generated by CoffeeScript 1.8.0
var Liquid, lib;

lib = require('../../lib');

Liquid = require('huginn-liquid');

lib.Li2Template = (function() {
  Li2Template.prototype.template = '';

  Li2Template.prototype._template = null;

  function Li2Template(template) {
    parse(template);
  }

  Li2Template.prototype.parse = function(template) {
    this.template = template;
    this._template = Liquid.Template.parse(template);
  };

  Li2Template.prototype.render = function(variables) {
    return this._template.render(variables);
  };

  return Li2Template;

})();

//# sourceMappingURL=li2_template.js.map
