#
# Alien Zone Configuration
#
name: Alien Zone

minWidth: 320
minHeight: 480
maxWidth: 640
maxHeight: 960
pageAlignHorizontally: true
pageAlignVertically: true
forceOrientation: false

splashKey: splashScreen
splashImg: assets/images/splash.png

showPreloadBar: false
preloadBarKey: preloadBar
preloadBarImg: 
preloadBgdKey: preloadBgd
preloadBgdImg: 

images:
      background:     assets/images/background.png
      board:          assets/images/board.png
      icon:           assets/images/d16a.png
      label:          assets/images/label.png
      scores:         assets/images/scores.png
      #  ui buttons
      playButton:     assets/images/buttons/play1.png
      scoreButton:    assets/images/buttons/score1.png
      creditsButton:  assets/images/buttons/credits1.png
      backButton:     assets/images/buttons/back1.png
      arrow_right:    assets/images/arrows/right.png
      arrow_left:     assets/images/arrows/left.png
      arrow_down:     assets/images/arrows/down.png
      arrow_lrot:     assets/images/arrows/lrot.png
      arrow_rrot:     assets/images/arrows/rrot.png
      # game pieces
      gem_blue:       assets/images/gems/blue.png
      gem_cyan:       assets/images/gems/cyan.png
      gem_green:      assets/images/gems/green.png
      gem_magenta:    assets/images/gems/magenta.png
      gem_orange:     assets/images/gems/orange.png
      gem_pink:       assets/images/gems/pink.png
      gem_red:        assets/images/gems/red.png
      gem_yellow:     assets/images/gems/yellow.png

copyrightText: Copyright 2014 Dark Overlord of Data
creditsText: |
  Program by darkoverlordofdata
  Background Graphics - http://www.nasa.gov
  Gems: http://opengameart.org/content/gem-tiles
  Based on: https://github.com/hugeen/createjs_match3

sprite:
levels:
