name: orion
version: 0.0.1
description: A sample web application
dependencies:
  browser: any
  dartemis: any
  play_phaser: any

dev_dependencies:
#  unittest: any
transformers:
- $dart2js:
    checked: false
    minify: true
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true
    csp: true
