#
# Alien Zed Configuration
#
name: Alien Zed

minWidth: 320
minHeight: 480
maxWidth: 640
maxHeight: 960
pageAlignHorizontally: true
pageAlignVertically: true
forceOrientation: false

splashKey: splashScreen
splashImg: assets/images/splash.png

showPreloadBar: false
preloadBarKey: preloadBar
preloadBarImg: 
preloadBgdKey: preloadBgd
preloadBgdImg: 

images:
sprite:
levels:

copyrightText: Copyright 2014 Dark Overlord of Data
creditsText: |
  Program by darkoverlordofdata
  Background Graphics - http://www.nasa.gov
  Gems: http://opengameart.org/content/gem-tiles
  Based on: https://github.com/hugeen/createjs_match3

